name: Update total experience in README

on:
  schedule:
    - cron: "0 0 * * *"   # 매일 00:00 UTC (KST 09:00) 실행
  workflow_dispatch:
  push:
    paths:
      - "README.md"
      - "scripts/calc_experience.py"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run calculator
        run: |
          pip install --upgrade pip
          python scripts/calc_experience.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore(readme): update total experience"
            git push
          fi
